//
// UserView.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct UserView: Codable {

    public var _id: UUID?
    public var firstName: String?
    public var lastName: String?
    public var middleName: String?
    public var phoneNumber: String?
    public var email: String?
    public var properties: [UserPropertyView]?

    public init(_id: UUID?, firstName: String?, lastName: String?, middleName: String?, phoneNumber: String?, email: String?, properties: [UserPropertyView]?) {
        self._id = _id
        self.firstName = firstName
        self.lastName = lastName
        self.middleName = middleName
        self.phoneNumber = phoneNumber
        self.email = email
        self.properties = properties
    }

    public enum CodingKeys: String, CodingKey {
        case _id = "id"
        case firstName
        case lastName
        case middleName
        case phoneNumber
        case email
        case properties
    }
    
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        _id = try? container.decode(UUID.self, forKey: ._id)
        firstName = try? container.decode(String.self, forKey: .firstName)
        lastName = try? container.decode(String.self, forKey: .lastName)
        middleName = try? container.decode(String.self, forKey: .middleName)
        email = try? container.decode(String.self, forKey: .email)
        properties = try? container.decode([UserPropertyView].self, forKey: .properties)

        phoneNumber = try? container.decode(String.self, forKey: .phoneNumber)

        if var phone = phoneNumber {
            phone = phone.replacingOccurrences(of: "[^0-9]", with: "", options: .regularExpression)


            if phone[phone.startIndex] != "7" && phone.count == 11 {
                phone.replaceSubrange(...phone.startIndex, with: "7")
            } else if phone.count == 10 {
                phone.insert(contentsOf: "7", at: phone.startIndex)
            }

            phoneNumber = phone
        }
    }
    
    public init() {}
}
