name: Test

on: 
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1

  build:
    name: test
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Create Debug file
        uses: 1arp/create-a-file-action@0.2
        with:
          path: 'ITLab'
          file: 'DebugConfig.xcconfig'
          content: ${{secrets.DEBUG}}

      - name: Create Release file
        uses: 1arp/create-a-file-action@0.2
        with:
          path: 'ITLab'
          file: 'Release.xcconfig'
          content: ${{secrets.RELEASE}}

      - name: Xcode build
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          project: ITLab.xcodeproj
          scheme: ITLab
          destination: platform=iOS Simulator,name=iPhone 12
          action: build

      - name: Xcode test
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          project: ITLab.xcodeproj
          scheme: ITLab
          destination: platform=iOS Simulator,name=iPhone 12
          build-settings: LOGIN=${{secrets.LOGIN}} PSW=${{secrets.PSW}}
          action: test

      - uses: actions/upload-artifact@v2
        with:
          name: report-test
          path: /Users/runner/Library/Developer/Xcode/DerivedData/ITLab-*/Logs/Test/*.xcresult
